description: >
  The default executor for this orb, using the official .NET SDK Docker image.
docker:
  - image: 'mcr.microsoft.com/dotnet/sdk:<<parameters.tag>>'
parameters:
  tag:
    default: '8.0'
    description: >
      Pick a specific mcr.microsoft.com/dotnet/sdk image variant:
      https://mcr.microsoft.com/en-us/artifact/mar/dotnet/sdk/tags
    type: string
